version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: forum-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d forum-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command: ["-path=/migrations/", "-database", "postgres://user:password@postgres:5432/forum-db?sslmode=disable", "up"]
    restart: on-failure

volumes:
  pgdata:
